framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
parameters:
    api_key:    "%env(MJ_APIKEY_PUBLIC)%"
    secret_key: "%env(MJ_APIKEY_PRIVATE)%"
    sender_name: "%env(SENDER_NAME)%"
    sender_email: "%env(SENDER_EMAIL)%"
    mj_token: "%env(MJ_TOKEN)%"