<?php

namespace ContainerBJ9T3h7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5xUAUK3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5xUAUK3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5xUAUK3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BoController::accueil' => ['privates', '.service_locator.P6R5cY4', 'get_ServiceLocator_P6R5cY4Service', true],
            'App\\Controller\\BoController::gestionAuth' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\NewsletterController::newsLetter' => ['privates', '.service_locator.YEc9LhB', 'get_ServiceLocator_YEc9LhBService', true],
            'App\\Controller\\NewsletterController::newsLetterDelete' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\NewsletterController::newsLetterList' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\NewsletterController::newsLetterUpdate' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController::loginBo' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::loginCa' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BoController:accueil' => ['privates', '.service_locator.P6R5cY4', 'get_ServiceLocator_P6R5cY4Service', true],
            'App\\Controller\\BoController:gestionAuth' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\NewsletterController:newsLetter' => ['privates', '.service_locator.YEc9LhB', 'get_ServiceLocator_YEc9LhBService', true],
            'App\\Controller\\NewsletterController:newsLetterDelete' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\NewsletterController:newsLetterList' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\NewsletterController:newsLetterUpdate' => ['privates', '.service_locator.7S.7XLu', 'get_ServiceLocator_7S_7XLuService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController:loginBo' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:loginCa' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BoController::accueil' => '?',
            'App\\Controller\\BoController::gestionAuth' => '?',
            'App\\Controller\\NewsletterController::newsLetter' => '?',
            'App\\Controller\\NewsletterController::newsLetterDelete' => '?',
            'App\\Controller\\NewsletterController::newsLetterList' => '?',
            'App\\Controller\\NewsletterController::newsLetterUpdate' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::loginBo' => '?',
            'App\\Controller\\SecurityController::loginCa' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BoController:accueil' => '?',
            'App\\Controller\\BoController:gestionAuth' => '?',
            'App\\Controller\\NewsletterController:newsLetter' => '?',
            'App\\Controller\\NewsletterController:newsLetterDelete' => '?',
            'App\\Controller\\NewsletterController:newsLetterList' => '?',
            'App\\Controller\\NewsletterController:newsLetterUpdate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:loginBo' => '?',
            'App\\Controller\\SecurityController:loginCa' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
