<?php

namespace ContainerBJ9T3h7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGestionAuthTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\GestionAuthType' shared autowired service.
     *
     * @return \App\Form\GestionAuthType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/GestionAuthType.php';

        return $container->privates['App\\Form\\GestionAuthType'] = new \App\Form\GestionAuthType();
    }
}
