<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBJ9T3h7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBJ9T3h7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBJ9T3h7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBJ9T3h7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBJ9T3h7\App_KernelDevDebugContainer([
    'container.build_hash' => 'BJ9T3h7',
    'container.build_id' => 'd2f66fc3',
    'container.build_time' => 1636474297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBJ9T3h7');
